In [1]:
import numpy as np
import pandas as pd

In [2]:
tn = pd.read_csv("True.csv",nrows=2000)
fn = pd.read_csv("Fake.csv",nrows=2000)
tn['class']=1
fn['class']=0
df=pd.concat([tn.head(2000),fn.head(2000)],ignore_index=True)
df = df.sample(frac=1).reset_index(drop=True)
df['News']=df['text']
#df

In [3]:
import nltk
#nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [5]:
TL = WordNetLemmatizer()
corpus = []
for i in range(0,4000):
    line = re.sub('[^a-zA-Z]',' ',df['News'][i]) #[char for char in text if char not in string.punctuation] 
    line = line.lower()
    line = line.split()
    line = [TL.lemmatize(word) for word in line if not word in set(stopwords.words('english'))]
    line = ' '.join(line)
    corpus.append(line)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
cv = CountVectorizer(binary=True)
x=cv.fit(corpus)
y = df['class'].values
#print([w for w in sorted(cv.vocabulary_.keys())])
feature = pd.DataFrame(cv.transform(corpus).toarray(),columns=cv.vocabulary_.keys())

In [36]:
cv2 = CountVectorizer()
x2=cv2.fit(corpus)
feature2 = pd.DataFrame(cv2.transform(corpus).toarray(),columns=cv2.vocabulary_.keys())

In [39]:
TV = TfidfVectorizer()
x3= TV.fit(corpus)
feature3 =pd.DataFrame(TV.transform(corpus).toarray(),columns=TV.vocabulary_.keys())

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
x_train , x_test , y_train , y_test = train_test_split(feature,df['class'],test_size=0.2)
print(x_train.shape)
print(x_test.shape)

(3200, 32459)
(800, 32459)


In [46]:
from sklearn.naive_bayes import MultinomialNB
# CountVectorizer(binary=True)
model = MultinomialNB()
model.fit(x_train,y_train)
predict = model.predict(x_test)
print(accuracy_score(y_test,predict)*100)
print(confusion_matrix(y_test,predict))

98.625
[[393   7]
 [  4 396]]


In [47]:
x_train2 , x_test2 , y_train2 , y_test2 = train_test_split(feature2,df['class'],test_size=0.2)
print(x_train2.shape)
print(x_test2.shape)
model2 = MultinomialNB()
model2.fit(x_train2,y_train2)
predict2 = model2.predict(x_test2)
print(accuracy_score(y_test2,predict2)*100)
print(confusion_matrix(y_test2,predict2))

(3200, 32459)
(800, 32459)
97.5
[[378  13]
 [  7 402]]


In [48]:
#TfidfVectorizer()
x_train3 , x_test3 , y_train3 , y_test3 = train_test_split(feature3,df['class'],test_size=0.2)
print(x_train3.shape)
print(x_test3.shape)
model3 = MultinomialNB()
model3.fit(x_train3,y_train3)
predict3 = model3.predict(x_test3)
print(accuracy_score(y_test3,predict3)*100)
print(confusion_matrix(y_test3,predict3))

(3200, 32459)
(800, 32459)
96.125
[[368  15]
 [ 16 401]]
